@startuml
'https://plantuml.com/class-diagram

interface Inode<B extends Iblock>
interface FileOperations
interface DirOperations
class FileInode<FileIblock>
class DirInode<DirIblock>

Inode <|-- FileInode
FileOperations <|-- FileInode
Inode <|-- DirInode
DirOperations <|-- DirInode

@enduml
